### ISSUE TITLE
🐛 Import aliases get malformed

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [NicolasRoehm/angular-vscode-cleaner#2]
`import { find as _find } from 'lodash';`
will be transformed to
`import { findas_find }                            from 'lodash';`
which is not functional anymore

**Comment by NicolasRoehm** [comment]
Fixed in https://github.com/NicolasRoehm/classify-ts-import/commit/b325c44889653497f7df5e6bc46a9216ba87440a
