### ISSUE TITLE
🐛 Type only imports get cleared

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [NicolasRoehm/angular-vscode-cleaner#3]
`import type { Ref, ComputedRef } from 'vue';`
transform to 
```
import { Ref }                                    from 'vue';
import { ComputedRef }                            from 'vue';
```
type is missing

**Comment by NicolasRoehm** [comment]
Fixed in https://github.com/NicolasRoehm/classify-ts-import/commit/b325c44889653497f7df5e6bc46a9216ba87440a
